// <auto-generated />
using System;
using ApexPredatorTrialsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApexPredatorTrialsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913100312_DbAdjustments")]
    partial class DbAdjustments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.GameEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.GameEventRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PlayerId");

                    b.ToTable("EventRegistrations");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.GameEventSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<int?>("NextScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasFilter("[MatchId] IS NOT NULL");

                    b.HasIndex("NextScheduleId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.GameMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.IpAddress", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.HasKey("Address");

                    b.ToTable("IpAddresses");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientAddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientAddress", "Timestamp");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("HumanPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("HunterPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("HumanPlayerId");

                    b.HasIndex("HunterPlayerId");

                    b.HasIndex("MapId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.MatchResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeConcluded")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoserDeaths")
                        .HasColumnType("int");

                    b.Property<int>("LoserId")
                        .HasColumnType("int");

                    b.Property<int>("LoserKills")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("NestsDestroyed")
                        .HasColumnType("int");

                    b.Property<int>("WinnerDeaths")
                        .HasColumnType("int");

                    b.Property<int>("WinnerId")
                        .HasColumnType("int");

                    b.Property<int>("WinnerKills")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoserId");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("WinnerId");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerStatsId")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerStatsId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.PlayerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HumanHoursPlayed")
                        .HasColumnType("int");

                    b.Property<string>("HumanRank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HunterHoursPlayed")
                        .HasColumnType("int");

                    b.Property<string>("HunterRank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LegendLevel")
                        .HasColumnType("int");

                    b.Property<int>("MutationLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayersStatistics");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.GameEvent", b =>
                {
                    b.HasOne("ApexPredatorTrialsAPI.Models.User", "Organizer")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.GameEventRegistration", b =>
                {
                    b.HasOne("ApexPredatorTrialsAPI.Models.GameEvent", "Event")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApexPredatorTrialsAPI.Models.Player", "Player")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.GameEventSchedule", b =>
                {
                    b.HasOne("ApexPredatorTrialsAPI.Models.GameEvent", "Event")
                        .WithMany("Schedules")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApexPredatorTrialsAPI.Models.Match", "Match")
                        .WithOne("Schedule")
                        .HasForeignKey("ApexPredatorTrialsAPI.Models.GameEventSchedule", "MatchId");

                    b.HasOne("ApexPredatorTrialsAPI.Models.GameEventSchedule", "NextSchedule")
                        .WithMany("PreviousSchedules")
                        .HasForeignKey("NextScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Event");

                    b.Navigation("Match");

                    b.Navigation("NextSchedule");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.Match", b =>
                {
                    b.HasOne("ApexPredatorTrialsAPI.Models.GameEvent", "Event")
                        .WithMany("Matches")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApexPredatorTrialsAPI.Models.Player", "HumanPlayer")
                        .WithMany("HumanMatches")
                        .HasForeignKey("HumanPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexPredatorTrialsAPI.Models.Player", "HunterPlayer")
                        .WithMany("HunterMatches")
                        .HasForeignKey("HunterPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexPredatorTrialsAPI.Models.GameMap", "Map")
                        .WithMany("Matches")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("HumanPlayer");

                    b.Navigation("HunterPlayer");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.MatchResults", b =>
                {
                    b.HasOne("ApexPredatorTrialsAPI.Models.Player", "Loser")
                        .WithMany()
                        .HasForeignKey("LoserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApexPredatorTrialsAPI.Models.Match", "Match")
                        .WithOne("MatchResults")
                        .HasForeignKey("ApexPredatorTrialsAPI.Models.MatchResults", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApexPredatorTrialsAPI.Models.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loser");

                    b.Navigation("Match");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.Player", b =>
                {
                    b.HasOne("ApexPredatorTrialsAPI.Models.PlayerStats", "PlayerStats")
                        .WithOne("Player")
                        .HasForeignKey("ApexPredatorTrialsAPI.Models.Player", "PlayerStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApexPredatorTrialsAPI.Models.User", "User")
                        .WithOne("Player")
                        .HasForeignKey("ApexPredatorTrialsAPI.Models.Player", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlayerStats");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.GameEvent", b =>
                {
                    b.Navigation("EventRegistrations");

                    b.Navigation("Matches");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.GameEventSchedule", b =>
                {
                    b.Navigation("PreviousSchedules");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.GameMap", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.Match", b =>
                {
                    b.Navigation("MatchResults");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.Player", b =>
                {
                    b.Navigation("EventRegistrations");

                    b.Navigation("HumanMatches");

                    b.Navigation("HunterMatches");
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.PlayerStats", b =>
                {
                    b.Navigation("Player")
                        .IsRequired();
                });

            modelBuilder.Entity("ApexPredatorTrialsAPI.Models.User", b =>
                {
                    b.Navigation("OrganizedEvents");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
